# Generated by Django 3.2 on 2024-04-17 18:43

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=20, verbose_name='Код авторизации'),
        ),
    ]
