# Generated by Django 4.0 on 2024-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_confirmation_code_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
