# Generated by Django 3.2 on 2024-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20240418_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moder', 'Moderator'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
